/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DataValueType: typeof import('./src/types/wikidata').DataValueType
  const EffectScope: typeof import('vue').EffectScope
  const SnakDataType: typeof import('./src/types/wikidata').SnakDataType
  const SnakType: typeof import('./src/types/wikidata').SnakType
  const UPLOAD_STATUS: typeof import('./src/types/image').UPLOAD_STATUS
  const WikidataEntity: typeof import('./src/types/wikidata').WikidataEntity
  const WikidataProperty: typeof import('./src/types/wikidata').WikidataProperty
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const botsStore: typeof import('./src/stores/bots.store').default
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createCopyrightLicenseClaim: typeof import('./src/composables/sdc').createCopyrightLicenseClaim
  const createCopyrightStatusClaim: typeof import('./src/composables/sdc').createCopyrightStatusClaim
  const createCreatorClaim: typeof import('./src/composables/sdc').createCreatorClaim
  const createExternalIdSnak: typeof import('./src/composables/sdc').createExternalIdSnak
  const createExternalIdStatement: typeof import('./src/composables/sdc').createExternalIdStatement
  const createHeightClaim: typeof import('./src/composables/sdc').createHeightClaim
  const createInceptionClaim: typeof import('./src/composables/sdc').createInceptionClaim
  const createMapillaryIdClaim: typeof import('./src/composables/sdc').createMapillaryIdClaim
  const createPinia: typeof import('pinia').createPinia
  const createPublishedInMapillaryClaim: typeof import('./src/composables/sdc').createPublishedInMapillaryClaim
  const createQuantitySnak: typeof import('./src/composables/sdc').createQuantitySnak
  const createQuantityStatement: typeof import('./src/composables/sdc').createQuantityStatement
  const createSomeValueSnak: typeof import('./src/composables/sdc').createSomeValueSnak
  const createSourceOfFileClaim: typeof import('./src/composables/sdc').createSourceOfFileClaim
  const createStatement: typeof import('./src/composables/sdc').createStatement
  const createStatusFromJob: typeof import('./src/composables/useBotStatus').createStatusFromJob
  const createStringSnak: typeof import('./src/composables/sdc').createStringSnak
  const createTimeSnak: typeof import('./src/composables/sdc').createTimeSnak
  const createTimeStatement: typeof import('./src/composables/sdc').createTimeStatement
  const createUrlSnak: typeof import('./src/composables/sdc').createUrlSnak
  const createWidthClaim: typeof import('./src/composables/sdc').createWidthClaim
  const createWikibaseItemSnak: typeof import('./src/composables/sdc').createWikibaseItemSnak
  const createWikibaseItemStatement: typeof import('./src/composables/sdc').createWikibaseItemStatement
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const formatDuration: typeof import('./src/composables/useFormatDuration').formatDuration
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getNumericId: typeof import('./src/composables/sdc').getNumericId
  const h: typeof import('vue').h
  const harborStore: typeof import('./src/stores/harbor.store').default
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const jobsStore: typeof import('./src/stores/jobs.store').default
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useAuthStore: typeof import('./src/stores/auth.store').useAuthStore
  const useBotStatus: typeof import('./src/composables/useBotStatus').default
  const useBotsApi: typeof import('./src/composables/useBotsApi').default
  const useBotsStore: typeof import('./src/stores/bots.store').useBotsStore
  const useCollections: typeof import('./src/composables/useCollections').useCollections
  const useCollectionsStore: typeof import('./src/stores/collections.store').useCollectionsStore
  const useCommons: typeof import('./src/composables/useCommons').useCommons
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useHarborApi: typeof import('./src/composables/useHarborApi').default
  const useHarborStore: typeof import('./src/stores/harbor.store').useHarborStore
  const useId: typeof import('vue').useId
  const useJobsApi: typeof import('./src/composables/useJobsApi').default
  const useJobsStore: typeof import('./src/stores/jobs.store').useJobsStore
  const useModel: typeof import('vue').useModel
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useWikidata: typeof import('./src/components/wikidata/useWikidata').useWikidata
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { FormattedDuration } from './src/composables/useFormatDuration'
  import('./src/composables/useFormatDuration')
  // @ts-ignore
  export type { StatusInfo, StatusConfig, BotStatus, Bot } from './src/types/bots'
  import('./src/types/bots')
  // @ts-ignore
  export type { Handler, Layout, CollectionsApiResponse } from './src/types/collections'
  import('./src/types/collections')
  // @ts-ignore
  export type { Process } from './src/types/harbor'
  import('./src/types/harbor')
  // @ts-ignore
  export type { Creator, Location, Dates, ExistingPage, Image, Metadata, MetadataKey, MetadataValue, Item, UploadStatus, UploadStatusUpdate, UploadIngestResponseItem } from './src/types/image'
  import('./src/types/image')
  // @ts-ignore
  export type { Job, JobRequest } from './src/types/jobs'
  import('./src/types/jobs')
  // @ts-ignore
  export type { WikibaseEntityType, NumericId, PropertyId, ItemId, DataValueEntityId, DataValueMonolingualText, DataValueQuantity, DataValueTime, StringDataValue, EntityIdDataValue, QuantityDataValue, TimeDataValue, UrlDataValue, DataValue, StringValueSnak, EntityIdValueSnak, ExternalIdValueSnak, QuantityValueSnak, TimeValueSnak, UrlValueSnak, ValueSnak, SomeValueSnak, NoValueSnak, Snak, Reference, Rank, Statement } from './src/types/wikidata'
  import('./src/types/wikidata')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly DataValueType: UnwrapRef<typeof import('./src/types/wikidata')['DataValueType']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly SnakDataType: UnwrapRef<typeof import('./src/types/wikidata')['SnakDataType']>
    readonly SnakType: UnwrapRef<typeof import('./src/types/wikidata')['SnakType']>
    readonly UPLOAD_STATUS: UnwrapRef<typeof import('./src/types/image')['UPLOAD_STATUS']>
    readonly WikidataEntity: UnwrapRef<typeof import('./src/types/wikidata')['WikidataEntity']>
    readonly WikidataProperty: UnwrapRef<typeof import('./src/types/wikidata')['WikidataProperty']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly botsStore: UnwrapRef<typeof import('./src/stores/bots.store')['default']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createCopyrightLicenseClaim: UnwrapRef<typeof import('./src/composables/sdc')['createCopyrightLicenseClaim']>
    readonly createCopyrightStatusClaim: UnwrapRef<typeof import('./src/composables/sdc')['createCopyrightStatusClaim']>
    readonly createCreatorClaim: UnwrapRef<typeof import('./src/composables/sdc')['createCreatorClaim']>
    readonly createExternalIdSnak: UnwrapRef<typeof import('./src/composables/sdc')['createExternalIdSnak']>
    readonly createExternalIdStatement: UnwrapRef<typeof import('./src/composables/sdc')['createExternalIdStatement']>
    readonly createHeightClaim: UnwrapRef<typeof import('./src/composables/sdc')['createHeightClaim']>
    readonly createInceptionClaim: UnwrapRef<typeof import('./src/composables/sdc')['createInceptionClaim']>
    readonly createMapillaryIdClaim: UnwrapRef<typeof import('./src/composables/sdc')['createMapillaryIdClaim']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly createPublishedInMapillaryClaim: UnwrapRef<typeof import('./src/composables/sdc')['createPublishedInMapillaryClaim']>
    readonly createQuantitySnak: UnwrapRef<typeof import('./src/composables/sdc')['createQuantitySnak']>
    readonly createQuantityStatement: UnwrapRef<typeof import('./src/composables/sdc')['createQuantityStatement']>
    readonly createSomeValueSnak: UnwrapRef<typeof import('./src/composables/sdc')['createSomeValueSnak']>
    readonly createSourceOfFileClaim: UnwrapRef<typeof import('./src/composables/sdc')['createSourceOfFileClaim']>
    readonly createStatement: UnwrapRef<typeof import('./src/composables/sdc')['createStatement']>
    readonly createStatusFromJob: UnwrapRef<typeof import('./src/composables/useBotStatus')['createStatusFromJob']>
    readonly createStringSnak: UnwrapRef<typeof import('./src/composables/sdc')['createStringSnak']>
    readonly createTimeSnak: UnwrapRef<typeof import('./src/composables/sdc')['createTimeSnak']>
    readonly createTimeStatement: UnwrapRef<typeof import('./src/composables/sdc')['createTimeStatement']>
    readonly createUrlSnak: UnwrapRef<typeof import('./src/composables/sdc')['createUrlSnak']>
    readonly createWidthClaim: UnwrapRef<typeof import('./src/composables/sdc')['createWidthClaim']>
    readonly createWikibaseItemSnak: UnwrapRef<typeof import('./src/composables/sdc')['createWikibaseItemSnak']>
    readonly createWikibaseItemStatement: UnwrapRef<typeof import('./src/composables/sdc')['createWikibaseItemStatement']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly formatDuration: UnwrapRef<typeof import('./src/composables/useFormatDuration')['formatDuration']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getNumericId: UnwrapRef<typeof import('./src/composables/sdc')['getNumericId']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly harborStore: UnwrapRef<typeof import('./src/stores/harbor.store')['default']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly jobsStore: UnwrapRef<typeof import('./src/stores/jobs.store')['default']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuthStore: UnwrapRef<typeof import('./src/stores/auth.store')['useAuthStore']>
    readonly useBotStatus: UnwrapRef<typeof import('./src/composables/useBotStatus')['default']>
    readonly useBotsApi: UnwrapRef<typeof import('./src/composables/useBotsApi')['default']>
    readonly useBotsStore: UnwrapRef<typeof import('./src/stores/bots.store')['useBotsStore']>
    readonly useCollections: UnwrapRef<typeof import('./src/composables/useCollections')['useCollections']>
    readonly useCollectionsStore: UnwrapRef<typeof import('./src/stores/collections.store')['useCollectionsStore']>
    readonly useCommons: UnwrapRef<typeof import('./src/composables/useCommons')['useCommons']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useHarborApi: UnwrapRef<typeof import('./src/composables/useHarborApi')['default']>
    readonly useHarborStore: UnwrapRef<typeof import('./src/stores/harbor.store')['useHarborStore']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useJobsApi: UnwrapRef<typeof import('./src/composables/useJobsApi')['default']>
    readonly useJobsStore: UnwrapRef<typeof import('./src/stores/jobs.store')['useJobsStore']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useWikidata: UnwrapRef<typeof import('./src/components/wikidata/useWikidata')['useWikidata']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}