/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    BatchesView: typeof import('./src/components/BatchesView.vue')['default']
    BatchUploadsView: typeof import('./src/components/BatchUploadsView.vue')['default']
    BotActions: typeof import('./src/components/BotActions.vue')['default']
    BotsDataTable: typeof import('./src/components/BotsDataTable.vue')['default']
    BotsTable: typeof import('./src/components/BotsTable.vue')['default']
    CollectionsControls: typeof import('./src/components/common/CollectionsControls.vue')['default']
    CollectionsEdit: typeof import('./src/components/common/CollectionsEdit.vue')['default']
    CollectionsInfoCard: typeof import('./src/components/common/CollectionsInfoCard.vue')['default']
    CollectionsTable: typeof import('./src/components/common/CollectionsTable.vue')['default']
    ExternalLink: typeof import('./src/components/common/ExternalLink.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IngestBatchInputs: typeof import('./src/components/common/IngestBatchInputs.vue')['default']
    IngestionStepper: typeof import('./src/components/common/IngestionStepper.vue')['default']
    IngestPagination: typeof import('./src/components/common/IngestPagination.vue')['default']
    IngestSelectionList: typeof import('./src/components/common/IngestSelectionList.vue')['default']
    ItemInputs: typeof import('./src/components/common/ItemInputs.vue')['default']
    JobStatusTag: typeof import('./src/components/JobStatusTag.vue')['default']
    MapillaryCollections: typeof import('./src/components/mapillary/MapillaryCollections.vue')['default']
    PropertyLabel: typeof import('./src/components/wikidata/PropertyLabel.vue')['default']
    StatementItem: typeof import('./src/components/wikidata/StatementItem.vue')['default']
    StatementsList: typeof import('./src/components/wikidata/StatementsList.vue')['default']
    UploadPreview: typeof import('./src/components/common/UploadPreview.vue')['default']
    UploadStatusTable: typeof import('./src/components/common/UploadStatusTable.vue')['default']
    ValueRenderer: typeof import('./src/components/wikidata/ValueRenderer.vue')['default']
    VR: typeof import('./src/components/wikidata/VR.vue')['default']
  }
}
