/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminView: typeof import('./src/components/AdminView.vue')['default']
    App: typeof import('./src/App.vue')['default']
    BatchesView: typeof import('./src/components/BatchesView.vue')['default']
    BatchUploadsView: typeof import('./src/components/BatchUploadsView.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Chip: typeof import('primevue/chip')['default']
    CollectionsControls: typeof import('./src/components/common/CollectionsControls.vue')['default']
    CollectionsEdit: typeof import('./src/components/common/CollectionsEdit.vue')['default']
    CollectionsInfoCard: typeof import('./src/components/common/CollectionsInfoCard.vue')['default']
    CollectionsTable: typeof import('./src/components/common/CollectionsTable.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    EditItem: typeof import('./src/components/common/EditItem.vue')['default']
    ErrorDisplay: typeof import('./src/components/common/ErrorDisplay.vue')['default']
    ExternalLink: typeof import('./src/components/common/ExternalLink.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    IngestionStepper: typeof import('./src/components/common/IngestionStepper.vue')['default']
    IngestPagination: typeof import('./src/components/common/IngestPagination.vue')['default']
    IngestSelectionList: typeof import('./src/components/common/IngestSelectionList.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemInputs: typeof import('./src/components/common/ItemInputs.vue')['default']
    MapillaryCollections: typeof import('./src/components/mapillary/MapillaryCollections.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    PropertyLabel: typeof import('./src/components/wikidata/PropertyLabel.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatementItem: typeof import('./src/components/wikidata/StatementItem.vue')['default']
    StatementsList: typeof import('./src/components/wikidata/StatementsList.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    UploadPreview: typeof import('./src/components/common/UploadPreview.vue')['default']
    UploadStatusTable: typeof import('./src/components/common/UploadStatusTable.vue')['default']
    ValueRenderer: typeof import('./src/components/wikidata/ValueRenderer.vue')['default']
    VR: typeof import('./src/components/wikidata/VR.vue')['default']
  }
  export interface GlobalDirectives {
    FocusTrap: typeof import('primevue/focustrap')['default']
  }
}
