// Generated by @asyncapi/modelina
// Do not edit manually

export type StructuredError =
  | DuplicateError
  | DuplicatedSdcNotUpdatedError
  | DuplicatedSdcUpdatedError
  | GenericError
  | TitleBlacklistedError

export type DataValue =
  | EntityIdDataValue
  | GlobeCoordinateDataValue
  | QuantityDataValue
  | TimeDataValue
  | StringDataValue
  | UrlDataValue

export type Snak =
  | NoValueSnak
  | SomeValueSnak
  | EntityIdValueSnak
  | ExternalIdValueSnak
  | GlobeCoordinateValueSnak
  | QuantityValueSnak
  | StringValueSnak
  | TimeValueSnak
  | UrlValueSnak

export type ValueSnak =
  | EntityIdValueSnak
  | ExternalIdValueSnak
  | GlobeCoordinateValueSnak
  | QuantityValueSnak
  | StringValueSnak
  | TimeValueSnak
  | UrlValueSnak

export type CreateBatch = {
  type: 'CREATE_BATCH'
}

export type FetchBatches = {
  data: FetchBatchesData
  type: 'FETCH_BATCHES'
}

export type FetchBatchesData = {
  page: number
  limit: number
  userid?: string
  filter?: string
}

export type FetchBatchUploads = {
  data: number
  type: 'FETCH_BATCH_UPLOADS'
}

export type FetchImages = {
  data: string
  type: 'FETCH_IMAGES'
}

export type RetryUploads = {
  data: number
  type: 'RETRY_UPLOADS'
}

export type SubscribeBatch = {
  data: number
  type: 'SUBSCRIBE_BATCH'
}

export type SubscribeBatchesList = {
  data: SubscribeBatchesListData
  type: 'SUBSCRIBE_BATCHES_LIST'
}

export type SubscribeBatchesListData = {
  filter?: string
  userid?: string
}

export type UnsubscribeBatch = {
  type: 'UNSUBSCRIBE_BATCH'
}

export type UnsubscribeBatchesList = {
  type: 'UNSUBSCRIBE_BATCHES_LIST'
}

export type Upload = {
  type: 'UPLOAD'
  data: UploadData
}

export type UploadData = {
  items: UploadItem[]
  handler: string
}

export type UploadItem = {
  id: string
  input: string
  title: string
  wikitext: string
  labels?: Label
  copyright_override?: boolean
}

export type Label = {
  language: string
  value: string
}

export type UploadSlice = {
  type: 'UPLOAD_SLICE'
  data: UploadSliceData
}

export type UploadSliceData = {
  batchid: number
  sliceid: number
  items: UploadItem[]
  handler: string
}

export type BatchCreated = {
  type: 'BATCH_CREATED'
  data: number
  nonce: string
}

export type BatchesList = {
  data: BatchesListData
  partial: boolean
  type: 'BATCHES_LIST'
  nonce: string
}

export type BatchesListData = {
  items: BatchItem[]
  total: number
}

export type BatchItem = {
  id: number
  created_at: string
  username: string
  userid: string
  stats: BatchStats
}

export type BatchStats = {
  completed: number
  duplicate: number
  failed: number
  in_progress: number
  queued: number
  total: number
}

export type BatchUploadsList = {
  data: BatchUploadsListData
  type: 'BATCH_UPLOADS_LIST'
  nonce: string
}

export type BatchUploadsListData = {
  batch: BatchItem
  uploads: BatchUploadItem[]
}

export type BatchUploadItem = {
  id: number
  status: string
  filename: string
  wikitext: string
  batchid?: number
  userid?: string
  key?: string
  handler?: string
  labels?: Label
  result?: string
  error?:
    | DuplicateError
    | DuplicatedSdcNotUpdatedError
    | DuplicatedSdcUpdatedError
    | GenericError
    | TitleBlacklistedError
  success?: string
  last_edited_by?: string
  created_at?: string
  updated_at?: string
  image_id?: string
}

export type DuplicateError = {
  links: ErrorLink[]
  message: string
  type?: 'duplicate'
}

export type ErrorLink = {
  title: string
  url: string
}

export type DuplicatedSdcNotUpdatedError = {
  links: ErrorLink[]
  message: string
  type?: 'duplicated_sdc_not_updated'
}

export type DuplicatedSdcUpdatedError = {
  links: ErrorLink[]
  message: string
  type?: 'duplicated_sdc_updated'
}

export type GenericError = {
  message: string
  type?: 'error'
}

export type TitleBlacklistedError = {
  message: string
  type?: 'title_blacklisted'
}

export type CollectionImageIds = {
  type: 'COLLECTION_IMAGE_IDS'
  data: string[]
  nonce: string
}

export type CollectionImages = {
  type: 'COLLECTION_IMAGES'
  data: CollectionImagesData
  nonce: string
}

export type CollectionImagesData = {
  images: Record<string, MediaImage>
  creator: Creator
}

export type MediaImage = {
  camera_make?: string
  camera_model?: string
  creator: Creator
  dates: Dates
  description?: string
  existing: ExistingPage[]
  height: number
  id: string
  is_pano?: boolean
  license?: string
  location: GeoLocation
  preview_url: string
  tags?: string[]
  thumbnail_url: string
  title: string
  url: string
  url_original: string
  width: number
}

export type Creator = {
  id: string
  username: string
  profile_url: string
}

export type Dates = {
  taken: string
}

export type ExistingPage = {
  url: string
}

export type GeoLocation = {
  accuracy?: number
  compass_angle: number
  latitude: number
  longitude: number
}

export type Error = {
  data: string
  type: 'ERROR'
  nonce: string
}

export type PartialCollectionImages = {
  type: 'PARTIAL_COLLECTION_IMAGES'
  data: PartialCollectionImagesData
  nonce: string
}

export type PartialCollectionImagesData = {
  images: MediaImage[]
  collection: string
}

export type Subscribed = {
  data: number
  type: 'SUBSCRIBED'
  nonce: string
}

export type TryBatchRetrieval = {
  type: 'TRY_BATCH_RETRIEVAL'
  data: string
  nonce: string
}

export type UploadCreated = {
  type: 'UPLOAD_CREATED'
  data: UploadCreatedItem[]
  nonce: string
}

export type UploadCreatedItem = {
  id: number
  status: string
  image_id: string
  input: string
  batchid: number
}

export type UploadsComplete = {
  data: number
  type: 'UPLOADS_COMPLETE'
  nonce: string
}

export type UploadsUpdate = {
  type: 'UPLOADS_UPDATE'
  data: UploadUpdateItem[]
  nonce: string
}

export type UploadUpdateItem = {
  id: number
  batchid: number
  status: string
  key: string
  error?:
    | DuplicateError
    | DuplicatedSdcNotUpdatedError
    | DuplicatedSdcUpdatedError
    | GenericError
    | TitleBlacklistedError
  success?: string
  handler: string
}

export type UploadSliceAck = {
  type: 'UPLOAD_SLICE_ACK'
  data: UploadSliceAckItem[]
  sliceid: number
  nonce: string
}

export type UploadSliceAckItem = {
  id: string
  status: string
}

export type Claims = Record<
  string,
  (
    | NoValueSnak
    | SomeValueSnak
    | EntityIdValueSnak
    | ExternalIdValueSnak
    | GlobeCoordinateValueSnak
    | QuantityValueSnak
    | StringValueSnak
    | TimeValueSnak
    | UrlValueSnak
  )[]
>

export type NoValueSnak = {
  snaktype: 'novalue'
  property: string
  hash?: string
}

export type SomeValueSnak = {
  snaktype: 'somevalue'
  property: string
  hash?: string
}

export type EntityIdValueSnak = {
  snaktype: 'value'
  property: string
  datatype: 'wikibase-item'
  datavalue: EntityIdDataValue
  hash?: string
}

export type EntityIdDataValue = {
  type: 'wikibase-entityid'
  value: DataValueEntityId
}

export type DataValueEntityId = {
  'entity-type': WikibaseEntityType
  'numeric-id': number
}

export enum WikibaseEntityType {
  ITEM = 'item',
  PROPERTY = 'property',
}

export type ExternalIdValueSnak = {
  snaktype: 'value'
  property: string
  datatype: 'external-id'
  datavalue: StringDataValue
  hash?: string
}

export type StringDataValue = {
  type: 'string'
  value: string
}

export type GlobeCoordinateValueSnak = {
  snaktype: 'value'
  property: string
  datatype: 'globe-coordinate'
  datavalue: GlobeCoordinateDataValue
  hash?: string
}

export type GlobeCoordinateDataValue = {
  type: 'globecoordinate'
  value: DataValueGlobeCoordinate
}

export type DataValueGlobeCoordinate = {
  latitude: number
  longitude: number
  altitude: number | null
  precision: number
  globe: string
}

export type QuantityValueSnak = {
  snaktype: 'value'
  property: string
  datatype: 'quantity'
  datavalue: QuantityDataValue
  hash?: string
}

export type QuantityDataValue = {
  type: 'quantity'
  value: DataValueQuantity
}

export type DataValueQuantity = {
  amount: string
  unit: string
  upperBound?: string | null
  lowerBound?: string | null
}

export type StringValueSnak = {
  snaktype: 'value'
  property: string
  datatype: 'string'
  datavalue: StringDataValue
  hash?: string
}

export type TimeValueSnak = {
  snaktype: 'value'
  property: string
  datatype: 'time'
  datavalue: TimeDataValue
  hash?: string
}

export type TimeDataValue = {
  type: 'time'
  value: DataValueTime
}

export type DataValueTime = {
  time: string
  timezone?: number
  before?: number
  after?: number
  precision?: number
  calendarmodel?: string
}

export type UrlValueSnak = {
  snaktype: 'value'
  property: string
  datatype: 'url'
  datavalue: UrlDataValue
  hash?: string
}

export type UrlDataValue = {
  type: 'string'
  value: string
}

export enum DataValueType {
  EXTERNAL_ID = 'external-id',
  GLOBECOORDINATE = 'globecoordinate',
  QUANTITY = 'quantity',
  STRING = 'string',
  TIME = 'time',
  WIKIBASE_ENTITYID = 'wikibase-entityid',
}

export type ItemId = `Q${number}`

export type PropertyId = `P${number}`

export enum Rank {
  DEPRECATED = 'deprecated',
  NORMAL = 'normal',
  PREFERRED = 'preferred',
}

export type Reference = {
  snaks: Record<
    string,
    (
      | NoValueSnak
      | SomeValueSnak
      | EntityIdValueSnak
      | ExternalIdValueSnak
      | GlobeCoordinateValueSnak
      | QuantityValueSnak
      | StringValueSnak
      | TimeValueSnak
      | UrlValueSnak
    )[]
  >
  'snaks-order'?: string[]
  hash?: string
}

export enum SnakDataType {
  EXTERNAL_ID = 'external-id',
  GLOBE_COORDINATE = 'globe-coordinate',
  QUANTITY = 'quantity',
  STRING = 'string',
  TIME = 'time',
  URL = 'url',
  WIKIBASE_ITEM = 'wikibase-item',
}

export type Statement = {
  mainsnak:
    | NoValueSnak
    | SomeValueSnak
    | EntityIdValueSnak
    | ExternalIdValueSnak
    | GlobeCoordinateValueSnak
    | QuantityValueSnak
    | StringValueSnak
    | TimeValueSnak
    | UrlValueSnak
  rank: Rank
  qualifiers?: Record<
    string,
    (
      | NoValueSnak
      | SomeValueSnak
      | EntityIdValueSnak
      | ExternalIdValueSnak
      | GlobeCoordinateValueSnak
      | QuantityValueSnak
      | StringValueSnak
      | TimeValueSnak
      | UrlValueSnak
    )[]
  >
  'qualifiers-order'?: string[]
  references?: Reference[]
  type?: 'statement'
  id?: string
}

export enum SnakType {
  NOVALUE = 'novalue',
  SOMEVALUE = 'somevalue',
  VALUE = 'value',
}

export type ClientMessage =
  | CreateBatch
  | FetchBatches
  | FetchBatchUploads
  | FetchImages
  | RetryUploads
  | SubscribeBatch
  | SubscribeBatchesList
  | UnsubscribeBatch
  | UnsubscribeBatchesList
  | Upload
  | UploadSlice

export type ServerMessage =
  | BatchCreated
  | BatchesList
  | BatchUploadsList
  | CollectionImageIds
  | CollectionImages
  | Error
  | PartialCollectionImages
  | Subscribed
  | TryBatchRetrieval
  | UploadCreated
  | UploadsComplete
  | UploadsUpdate
  | UploadSliceAck
