// Generated by @asyncapi/modelina
// Do not edit manually

export type WsChannel =
  | BatchesList
  | BatchUploadsList
  | CollectionImages
  | Error
  | Subscribed
  | UploadCreated
  | UploadsComplete
  | UploadsUpdate

export type FetchBatches = {
  data: FetchBatchesData
  type: 'FETCH_BATCHES'
}

export type FetchBatchesData = {
  page: number
  limit: number
  userid?: string
  filter?: string
}

export type FetchBatchUploads = {
  data: number
  type: 'FETCH_BATCH_UPLOADS'
}

export type FetchImages = {
  data: string
  type: 'FETCH_IMAGES'
}

export type RetryUploads = {
  data: number
  type: 'RETRY_UPLOADS'
}

export type SubscribeBatch = {
  data: number
  type: 'SUBSCRIBE_BATCH'
}

export type SubscribeBatchesList = {
  data: SubscribeBatchesListData
  type: 'SUBSCRIBE_BATCHES_LIST'
}

export type SubscribeBatchesListData = {
  filter?: string
  userid?: string
}

export type UnsubscribeBatch = {
  type: 'UNSUBSCRIBE_BATCH'
}

export type UnsubscribeBatchesList = {
  type: 'UNSUBSCRIBE_BATCHES_LIST'
}

export type Upload = {
  type: 'UPLOAD'
  data: UploadData
}

export type UploadData = {
  items: UploadItem[]
  handler?: string
}

export type UploadItem = {
  id: string
  input: string
  title: string
  wikitext: string
  labels?: Record<string, string>
  sdc?: string
}

export type BatchesList = {
  data: BatchesListData
  type: 'BATCHES_LIST'
}

export type BatchesListData = {
  items: BatchItem[]
  total: number
}

export type BatchItem = {
  id: number
  created_at: string
  username: string
  userid: string
  stats: BatchStats
}

export type BatchStats = {
  completed: number
  duplicate: number
  failed: number
  in_progress: number
  queued: number
  total: number
}

export type BatchUploadsList = {
  data: BatchUploadsListData
  type: 'BATCH_UPLOADS_LIST'
}

export type BatchUploadsListData = {
  batch: BatchItem
  uploads: BatchUploadItem[]
}

export type BatchUploadItem = {
  id: number
  status: string
  filename: string
  wikitext: string
  batchid?: number
  userid?: string
  key?: string
  handler?: string
  sdc?: string
  labels?: Record<string, string>
  result?: string
  error?: DuplicateError | GenericError
  success?: string
  created_at?: string
  updated_at?: string
  image_id?: string
}

export type DuplicateError = {
  links: ErrorLink[]
  message: string
  type: 'duplicate'
}

export type ErrorLink = {
  title: string
  url: string
}

export type GenericError = {
  message: string
  type: 'error'
}

export type CollectionImages = {
  type: 'COLLECTION_IMAGES'
  data: CollectionImagesData
}

export type CollectionImagesData = {
  images: Record<string, MediaImage>
  creator: Creator
}

export type MediaImage = {
  camera_make?: string
  camera_model?: string
  creator: Creator
  dates: Dates
  description?: string
  existing: ExistingPage[]
  height: number
  id: string
  is_pano?: boolean
  license?: string
  location: GeoLocation
  preview_url: string
  tags?: string[]
  thumbnail_url: string
  title: string
  url: string
  url_original: string
  width: number
}

export type Creator = {
  id: string
  username: string
  profile_url: string
}

export type Dates = {
  taken: string
}

export type ExistingPage = {
  url: string
}

export type GeoLocation = {
  accuracy?: number
  compass_angle: number
  latitude: number
  longitude: number
}

export type Error = {
  data: string
  type: 'ERROR'
}

export type Subscribed = {
  data: number
  type: 'SUBSCRIBED'
}

export type UploadCreated = {
  type: 'UPLOAD_CREATED'
  data: UploadCreatedItem[]
}

export type UploadCreatedItem = {
  id: number
  status: string
  image_id: string
  input: string
  batchid: number
}

export type UploadsComplete = {
  data: number
  type: 'UPLOADS_COMPLETE'
}

export type UploadsUpdate = {
  type: 'UPLOADS_UPDATE'
  data: UploadUpdateItem[]
}

export type UploadUpdateItem = {
  id: number
  batchid: number
  status: string
  key: string
  error?: DuplicateError | GenericError
  success?: string
  handler: string
}

export type ClientMessage =
  | FetchBatches
  | FetchBatchUploads
  | FetchImages
  | RetryUploads
  | SubscribeBatch
  | SubscribeBatchesList
  | UnsubscribeBatch
  | UnsubscribeBatchesList
  | Upload

export type ServerMessage =
  | BatchesList
  | BatchUploadsList
  | CollectionImages
  | Error
  | Subscribed
  | UploadCreated
  | UploadsComplete
  | UploadsUpdate

export type StructuredError = DuplicateError | GenericError
